"""empty message

Revision ID: 100477a524c3
Revises: 6988190f1309
Create Date: 2023-05-03 13:49:46.887958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100477a524c3'
down_revision = '6988190f1309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')



    # ### end Alembic commands ###
